# Generated by Django 4.2.1 on 2023-05-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.IntegerField()),
                ('employeename', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
                ('Designation', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
