# Generated by Django 4.2.1 on 2023-07-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product')),
                ('title', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=10)),
                ('title1', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='view',
        ),
    ]
